/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;
import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
/**
 *
 * @author IM
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form Ahorcado
     */
    public Ahorcado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerete = new javax.swing.JButton();
        lblWord = new java.awt.Label();
        txtLetra = new java.awt.TextField();
        btnTry = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        lblintentos = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerete.setText("Generar palabra");
        btnGenerete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        getContentPane().add(lblWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 280, 36));

        txtLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(txtLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 45, -1));
        txtLetra.getAccessibleContext().setAccessibleName("");

        btnTry.setText("Intentar");
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });
        getContentPane().add(btnTry, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 280, 40));

        lblintentos.setText("Intentos Restantes: 5");
        getContentPane().add(lblintentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 140, 20));
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 90, 60));

        lblBackGround.setBackground(new java.awt.Color(255, 153, 0));
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/AhorcadoBackGround2.jpg"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Word w = new Word();
        Chances C = new Chances();
    private void btnGenereteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereteActionPerformed
        // TODO add your handling code here:
        lblWord.setText("");
        String[] x = {"PERRO", "GATO", "COMPUTADORA", "PROGRAMACION", "ZAPATO", "PATINETA", "UKELELE", "MANGO", "BOTELLA",
        "MARCIANOS", "ESCRITORIO", "VAPOR", "ORIENTE", "CORONAVIRUS", "VIKINGOS", "IDIOMA", "ESPAÑOL", "CUARENTENA"};
        Random rand = new Random();

        int n = rand.nextInt(17);
        String SelectedWord = x [n];
        
        System.out.println(SelectedWord);
        int WordLength = SelectedWord.length();
        
        for(int i = 0; i < WordLength; i++){
            String lblText = lblWord.getText();
            lblWord.setText(lblText + " _");
        }
        w.setWord(SelectedWord);
    }//GEN-LAST:event_btnGenereteActionPerformed

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
        lblMsg.setText("");
        if (txtLetra.getText().length()!= 1 ){
            lblMsg.setText("Cantidad de caracteres invalida");
        }
        else {
            w.setLetter(txtLetra.getText().toUpperCase().charAt(0));
                if(w.FindLetter(w.getWord(), w.getLetter())){
                    lblWord.setText(w.ReplaceLetter(lblWord.getText(), w.getWord(), w.getLetter()));
                }else{
                    C.setIntentos_Fallidos(C.getIntentos_Fallidos()+1);
                    lblintentos.setText("Intentos Restantes: "+C.Intentos_Restantes(C.getIntentos_Totales(), C.getIntentos_Fallidos()));
                    lblHead.setIcon(new ImageIcon(getClass().getResource("head3.png")));
                }
        }
        txtLetra.setText("");
    }//GEN-LAST:event_btnTryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
        
        
    }//Fin Main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerete;
    private javax.swing.JButton btnTry;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblMsg;
    private java.awt.Label lblWord;
    private javax.swing.JLabel lblintentos;
    private java.awt.TextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
